### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by jareware** [lukasmartinelli/docker-chronograf#2]
There's already a v0.4 out; would you want to upgrade this repo and [this image](https://hub.docker.com/r/lukasmartinelli/chronograf/) to match, and re-push with a `0.4.0` tag? Would be tremendous. :)

**Comment by jareware** [comment]
For whatever reason, the [automated build](https://hub.docker.com/r/lukasmartinelli/chronograf/builds/) hasn't succeeded. Do you see any details, being the owner? For me it just gives a blank page when I look at the build details.

**Comment by lukasmartinelli** [comment]
I don't have access to a computer abroad. Will check back once I'm back.
Thanks for the fix provided - sometimes the Docker build can fail for weird reasons. Let's check if your newest commits solve the problem.

**Comment by jareware** [comment]
Thanks! :)

**Comment by lukasmartinelli** [comment]
I don't think DockerHub supports `ARG` in automated builds yet. As soon this is implemented I will switch back to using `ARG` but for now we better use `ENV CHRONOGRAF_VERSION=0.4.0` as in https://github.com/lukasmartinelli/docker-chronograf/commit/80e9b4e18562a8b682cdc6d6e90e8fe95a635c18.

**Comment by jareware** [comment]
Oh, OK, that would explain it. Weird how Docker Inc is lagging behind in supporting Docker features...

It's not possible to override ENV vars during build time though, is it?

**Comment by lukasmartinelli** [comment]
> It's not possible to override ENV vars during build time though, is it?

Didn't see any option in Docker Hub yet. But I'm sure this will come soon.
Most official repos are using different folders (not even tags) for different versions.

There is a way to support both (last comment in https://github.com/docker/docker/issues/6822)
But DockerHub fails on the `ARG` instruction so this is not possible as well.
